package holdhus.developer_test.controller;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import holdhus.developer_test.entity.Film;
import holdhus.developer_test.repository.FilmRepository;

@RestController
@RequestMapping("/films")
public class FilmsController {

    @Autowired // This means to get the bean called userRepository
               // Which is auto-generated by Spring, we will use it to handle the data
    private FilmRepository filmRepository;

    @GetMapping
    public @ResponseBody Iterable<Film> getFilms() {
        // TODO return only a page
        // This returns a JSON or XML with the users
        return filmRepository.findAll();
    }
}
